#database configuration
spring.datasource.url=jdbc:postgresql://dpg-daa4phmk1f9s73ffg2g0-a.oregon-postgres.render.com/moneymanager_6pva
spring.datasource.username=moneymanager_6pva_user
spring.datasource.password=rZdMVkuu6NMoWsZRBJCFOHYMPwyWPIks